server:
  port: 9999
spring:
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      # 配置中心
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
    gateway:
      routes: #配置路由路径
        - id: sudoku-auth-route
          uri: lb://sudoku-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: sudoku-auth-route
          uri: lb://sudoku-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: sudoku-ums-route
          uri: lb://sudoku-ums
          predicates:
            - Path=/ums/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8000/getPublicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:

# 配置白名单路径
white-list:
  urls:
    - "/auth/oauth/token"
    - "/auth/captcha/captchaImage"
    - "/ums/security/login"
    - "/ums/security/register"

common:
  core:
    projectPackage: 'com.zumin.sudoku.gateway'