version: '3'
services:
  dc-mysql:
    image: mysql:8.0.24
    container_name: dc-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - 3306:3306
    volumes:
      - /mydata/dc/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/dc/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/dc/mysql/log:/var/log/mysql #日志文件挂载
      - /mydata/dc/mysql/init:/docker-entrypoint-initdb.d #初始化目录挂载
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  dc-redis:
    image: redis:5.0
    container_name: dc-redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/dc/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
  dc-nginx:
    image: nginx:latest
    container_name: dc-nginx
    volumes:
      - /mydata/dc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /mydata/dc/nginx/html:/usr/share/nginx/html
      - /mydata/dc/nginx/log:/var/log/nginx
    privileged: true
    ports:
      - 80:80
  dc-nacos:
    image: nacos/nacos-server:1.4.1
    container_name: dc-nacos
    depends_on:
      - dc-mysql
    environment:
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: dc-mysql
      MODE: standalone
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      JVM_XMS: 256m
      JVM_XMX: 256m
    ports:
      - 8848:8848
  dc-sentinel:
    image: bladex/sentinel-dashboard:1.7.2
    container_name: dc-sentinel
    ports:
      - 8858:8858
  dc-zipkin:
    image: openzipkin/zipkin:2.12.9
    container_name: dc-zipkin
    ports:
      - 9411:9411
