server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
    password:

  #数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sudoku_cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

common:
  web:
    data-binding: false
    exception-handler: false
    response: false
  core:
    projectPackage: 'com.zumin.sudoku.game'

#验证码配置
captcha:
  #长度
  width: 112
  #宽度
  height: 36
  #字符个数
  codeNumber: 4
  #干扰线个数
  lineCount: 100
  #有效期
  expireTime: 5
  #是否验证码
  enabled: true